---

services:
  exporter-node:
    image: quay.io/prometheus/node-exporter:latest
    container_name: exporter-node
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:9100'
    # network_mode: host
    # pid: host
    restart: unless-stopped
    ports:
      - "9100:9100"
    expose:
      - 9100
    networks:
      - monitoring
    volumes:
      - '/:/host:ro,rslave'
